apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8gb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: k8gb
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: k8gb-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    k8gb:
      dnsZones:
        - parentZone: "aksine-am.com" # -- parent zone which would contain gslb zone to delegate (same meaning as the old edgeDNSZone)
          loadBalancedZone: "blogtest.aksine-am.com" # -- zone controlled by gslb (same meaning as the old dnsZone)
      # -- used for places where we need to distinguish between different Gslb instances
      clusterGeoTag: "doh"
      # -- comma-separated list of external gslb geo tags to pair with
      extGslbClustersGeoTags: "doh,aus"

    cloudflare:
      # -- Enable Cloudflare provider
      enabled: true
      # -- Cloudflare Zone ID
      zoneID: 45deb80a1a445f84071406f5cd3ed72a
      # -- Configure how many DNS records to fetch per request
      # see https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md#throttling
      dnsRecordsPerPage: 5000

    # coredns:
    #   isClusterService: false
    #   serviceType: LoadBalancer # <== expose UDP DNS traffic via external load balancer
    #   service:
    # # clusterIP: ""
    # # clusterIPs: []
    #     loadBalancerIP: "10.0.0.77"