apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb

spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
