

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yt-dl
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: app-template-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: alexta69/metube
              tag: "latest"
                # -- environment variables.
                # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            env:
              # -- Set the container timezone
              TZ: Asia/Qatar
              # -- Specify the user ID the application will run as
              UID: "1000"
              # -- Specify the group ID the application will run as
              GID: "1000"





    service:
      main:
        controller: main
        ports:
          http:
            port: 8081

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      main:
        enabled: true
        hosts:
          - host: yt-dl.aksine.lcl
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http


    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      downloads:
        enabled: true
        existingClaim: yt-dl-pvc
        globalMounts:
          - path: /downloads