apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts

