apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich-charts
  namespace: flux-system
spec:
  interval: 1h
  timeout: 3m
  url: https://immich-app.github.io/immich-charts