apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1m0s
  path: ./cluster/doh/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
