apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tshikepe-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tshikepe.aksine-am.com`)
      kind: Rule
      services:
        - name: pth-frigate
          port: 8971
  tls:
    secretName: aksine-am-com-tls