apiVersion: v1
kind: Service
metadata:
  name: pth-frigate
  namespace: default
spec:
  ports:
    - name: http
      port: 8971
      targetPort: 8971
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pth-frigate
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.21
    ports:
      - name: http
        port: 8971