---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1m0s
  path: ./cluster/doh/infra/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-app
  interval: 1m0s
  path: ./cluster/doh/infra/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-issuers
  interval: 1m0s
  path: ./cluster/doh/infra/cert-manager/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

