apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - webdav-cephfs-pv.yaml
  - webdav-cephfs-pvc.yaml
  - webdav-smb-pv.yaml
  - webdav-smb-pvc.yaml
  - webdav-secret.yaml