---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webdav-smb-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: webdav-smb-pv
  storageClassName: smb
