apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: navidrome
      version: 0.0.6
      sourceRef:
        kind: HelmRepository
        name: navidrome-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    image:
      tag: "0.57.0"
    persistence:
      music:
        enabled: true
        type: pvc
        existingClaim: navidrome-lib-pvc
        mountPath: /music
      config:
        enabled: true
        type: pvc
        existingClaim: navidrome-app-pvc
        mountPath: /data
    #service:
    #  main:
    #    type: "LoadBalancer"
    ingress:
      main:
        # -- Enables or disables the ingress
        enabled: true

        #ngressClassName: nginx
        hosts:
        - host: navidrome.aksine.lcl
          paths:
              - path: /
