apiVersion: v1
kind: Secret
metadata:
    name: navidrome-secret
    namespace: default
type: Opaque
stringData:
  ND_LASTFM_APIKEY: 8267a7a2c58bcccaab3d5c90a6a680d1
  ND_LASTFM_SECRET: 96f995c7208c49b74f02b295f0fbca79