apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:

    installCRDs: true
    replicaCount: 3
    # extraArgs:
    #   - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
    #   - --dns01-recursive-nameservers-only
    #   - --feature-gates=AdditionalCertificateOutputFormats=true
    # featureGates: "AdditionalCertificateOutputFormats=true"
    # webhook:
    #   extraArgs:
    #     - --feature-gates=AdditionalCertificateOutputFormats=true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
